# Generated by Django 5.2.13 on 2026-04-12 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('guardian', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('college', models.CharField(blank=True, max_length=150)),
                ('year', models.CharField(blank=True, max_length=20)),
                ('joined_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
