# Generated by Django 5.2.13 on 2026-04-13 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='course',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='student',
        ),
        migrations.AddField(
            model_name='fee',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='enrollments.enrollment'),
        ),
    ]
